version: "3"

services:
  traefik:
    container_name: "traefik"
    image: "traefik:latest"
    networks: [web]
    ports:
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=web"
      - "--certificatesresolvers.cloudflareresolver.acme.dnschallenge=true"
      - "--certificatesresolvers.cloudflareresolver.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.cloudflareresolver.acme.email=$CF_API_EMAIL"
      - "--certificatesresolvers.cloudflareresolver.acme.storage=/letsencrypt/acme.json"
    environment:
      - "CF_API_EMAIL=$CF_API_EMAIL"
      - "CF_API_KEY=$CF_API_KEY"

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/etc/traefik/cloudflare-acme:/letsencrypt"
      
networks:
  web:
    external: true