version: "2.1"
services:
  unifi-network-application:
    image: lscr.io/linuxserver/unifi-network-application:latest
    container_name: unifi-network-application
    depends_on:
      - unifi-network-application-db
    networks:
      [unifi-network-application]
      #- web
      #- mongo_net
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MONGO_HOST=unifi-network-application-db
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi
      - MONGO_USER=$MONGODB_USER #unifi
      - MONGO_PASS=$MONGODB_PASSWORD #P9TPF8bgvZ3Kyyz9HcMLzpN47cRBua
      #- MONGO_HOST=172.15.0.1
      #- MONGO_PORT=27017
      #- MONGO_DBNAME=unifi-db
      - MEM_LIMIT=1024 #optional
      - MEM_STARTUP=1024 #optional
      #- MONGO_TLS= #optional
      #- MONGO_AUTHSOURCE= #optional
    volumes:
      - /path/to/data:/config
    ports:
      - 1900:1900/udp # Required for 'Make controller discoverable on L2 network' option
      - 3478:3478/udp # Unifi STUN port
      - 5514:5514/udp # Remote syslog port
      - 6789:6789 # For mobile throughput test
      - 8081:8080 # Required for device communication
      - 8443:8443 # Unifi web admin, guest portal HTTPS redirect port
      - 8833:8843 # Unifi guest portal HTTPS redirect port
      - 8880:8880 # Unifi guest portal HTTP redirect port
      - 10001:10001/udp # Required for AP discovery
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.router-unifi-network-application.entrypoints=web"
      - "traefik.http.routers.router-unifi-network-application.rule=Host(`uc.matthewford.dev`)"
      - "traefik.http.services.unifi-network-application.loadbalancer.server.port=8443"

  unifi-network-application-db:
    container_name: unifi-network-application-db
    image: mongo:4.4.26-focal
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: unifi-db
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASSWORD
    #user: ${MONGODB_USER}:$MONGODB_USER
    networks:
      - unifi-network-application

networks:
  unifi-network-application:
#  web:
#    external: true
#  mongo_net:
