version: "3"

services:
  traefik:
    container_name: "traefik"
    image: "traefik:latest"
    networks: [web]
    ports:
      - "8080:8080" # The Web UI (enabled by --api.insecure=true)
      - "80:80"
      - "443:443"
    environment:
      - "CF_API_EMAIL=$CF_API_EMAIL"
      - "CF_API_KEY=$CF_API_KEY"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/etc/traefik/cloudflare-acme:/letsencrypt"
    command:
      # Logging
      - --log.level=DEBUG

      # Globals
      - --global.checknewversion=true
      - --global.sendanonymoususage=false

      # Dashboard
      - --api.dashboard=true
      - --api.insecure=true

      # Entrypoints
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443

      # ACME configuration
      - --certificatesresolvers.cloudflareresolver.acme.dnschallenge=true
      - --certificatesresolvers.cloudflareresolver.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.cloudflareresolver.acme.email=$CF_API_EMAIL
      - --certificatesresolvers.cloudflareresolver.acme.storage=/letsencrypt/acme.json

      # Providers
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=web

      - --serversTransport.insecureSkipVerify=true

networks:
  web:
    external: true
